### ISSUE TITLE
Develop ogni tanto da "Il file è stato modificato" fuori dall'editor

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#10]
Ogni tanto capita che il develop segnali che il file è stato modificato dall'esterno senza che sia vero.

**Comment by mariocarmelo** [comment]
Con gli ultimi gestori questo errore non mi è più capitato.

**Comment by nippur72** [comment]
con #186 la funzione di monitoraggio dei files aperti è stata rimossa.
