### ISSUE TITLE
DocumentiMagazzino mod. 2.08

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#101]
Miglioramenti alla gestione del margine lordo. modifiche alla minifinestra. Inserimento nuovo help.

**Comment by studioReggio** [comment]
Ho modificato la select della browse di ricerca (BrowserAcquimov) affinchè includa anche documenti che per vari motivi hanno l'Id magazzino =0 , 
però ora c'è un altro problema, cioè visualizzando il documento con idmag=0 non ci si accorge che il magazzino è effettivamente zero perchè il campo magazzino non ha il collegamento alla tabella docmag, è solo un campo in memoria. 
Quindi stabiliamo se questo campo è logicamente modificabile , dopodichè si fanno le dovute correzioni.

**Comment by nippur72** [comment]
@studioReggio se è ancora valido il problema di idmag di cui sopra, potresti aprire un ticket specifico?
