### ISSUE TITLE
Possibilità di stampare le query di Esplora Database  

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#117]
Sarebbe molto utile poter stampare con  report le query in Esplora DataBase, soppianterebbero moltissimi programmi di servizio che ora non abbiamo.

**Comment by nippur72** [comment]
una cosa molto simile a questo è fare una `Browser` della vista e stamparla poi con la funzione di stampa della browse.

**Comment by studioReggio** [comment]
OK, query trasportabile su Excel selezionando tutte le righe della query , poi CRTL INS , esporta dati, e SHIFT INS su una foglio vuoto di excel , quindi stampabile.
