### ISSUE TITLE
Documenti di Magazzino - aggiornamento quantità  in magazzino negativa 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#121]
L'aggiornamento della quantità negli articoli nel magazzino alcune volte sbaglia ponendo valori negativi. 
Sarebbe opportuno passare l'ID dell'articolo da aggiornare nelle funzioni di aggiornamento.

**Comment by studioReggio** [comment]
Avevo fatto una versione di prova che ho dato tempo fa ad un cliente , pareva funzionasse, dove conservo TabGrigliaCorpo.Posizione  prima di ogni chiamata a AumentaQuantitaMagazzino
quindi per esempio in cambiato_quantita prima di AggiornaImportoRigo,   e laddove i cicli sulla griglia potrebbero sporcare la posizione, per esempio prima di CalcolaTotaliCorpo  . (La posizione viene riassegnata subito dopo questi cicli).

**Comment by nippur72** [comment]
duplicato di #86
