### ISSUE TITLE
Combox evento scelto

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#123]
Verificare le condizioni per le quali scatta l'evento `_Scelto()`

**Comment by nippur72** [comment]
Il problema risiede nel fatto che impostando `ComboBox1.Posizione = ...` scatta l'evento `Scelto()`.

Dobbiamo decidere se cambiare questo comportamento.

**Comment by studioReggio** [comment]
L'errore nasce dal fatto che c'è confusione tra assegnazione ed evento, cioè tra la visualizzazione  e la modifica nella combobox per cambiarne il valore. 
Infatti per il  #126 l'evento _Scelto deve scattare solo se l'operatore sceglie di cambiare il valore della combobox, e non anche quando ricerco e visualizzo un articolo , invece ora scatta per entrambi. (provare a visualizzare diversi articoli con un debug nell'evento ComboboxClassificazione_scelto, è palese)

**Comment by nippur72** [comment]
Dopo averci pensato un pò, sono propenso a mantenere il comportamento attuale, che poi è quello che prevede la libreria `WinForm`. 

Per ora etichetto a bassa priorità, poi si vedrà.

**Comment by nippur72** [comment]
Chiudo perchè il problema è scaturito da codice scritto male piuttosto che da un problema del componente `ComboBox`.
