### ISSUE TITLE
Messaggio incongruente nell'apertura database 

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#124]
Si segnala un messaggio incongruente affatto nuovo ma che è giusto eliminare.
 All'avvio di sessione, Portento se chiede le credenziali di accesso e l'operatore rinuncia ed esce attraverso il tasto rosso X e senza avere digitato alcunché compare comunque il messaggio:"Impossibile proseguire l'operazione è richiesta l'autenticazione ...".

**Comment by nippur72** [comment]
Se adesso l'utente chiude la finestra, l'errore non viene mostrato ma semplicemente il modulo si chiude in maniera "silenziosa".
