### ISSUE TITLE
Articoli rev. 2.11 produce errore .EOF nell'evento _Scelto in ricerca articoli 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#126]
Il problema del #123 si verifica anche dentro Articoli semplicemente richiamando in ricerca un articolo  e poi un altro , senza uscire

**Comment by nippur72** [comment]
semplicemente era codice scritto male, non solo le combobox, ma anche i pulsanti non devono essere abilitati quando il record è su `eof`.
