### ISSUE TITLE
Documenti magazzino - se si cambia intestazione non aggiorna la P.D. 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#130]
Se in una fattura si modifica l'intestatario , nel s/conto della Partita Doppia rimane il vecchio intestatario.  Comovditte è esatto, Comovcon no.

**Comment by nippur72** [comment]
ho risolto così: dopo il cambio di intestatario, il documento è posto "in elaborazione", in modo tale che il successivo "aggiorna" ricalcoli anche il comovcon.
