### ISSUE TITLE
DEVELOP - urge ripristinare il segnalibro (ALT B) 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#137]
E' diventato della massima importanza ripristinare il segnalibro (ALT B) , si perde troppo tempo a saltare da un punto all'altro di un file, alla fine si perde la concentrazione oltre che la pazienza.

**Comment by nippur72** [comment]
Assegnata bassa priorità in quanto adesso è possibile passare al vecchio editor

**Comment by studioReggio** [comment]
Ora che esiste la possibilità di scegliere , nel menu Opzioni del develop, l'uso del vecchio editor con il segnalibro , anche se dà qualche problemino, del tipo "il file è stato cancellato vuoi chiudere la sua pagina di editor?" ogni volta che torno dal Mask, chiudo io questo issue.
