### ISSUE TITLE
Aumentare dimensioni del font "sistema"

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#139]
Come qualcuno ha già notato i caratteri di Portento sono diventati "piccoli" da vedersi a video.

Questo non perchè si sono rimpiccioliti, ma perchè nel corso degli ultimi anni la risoluzione dei monitor è aumentata, ed è molto comune che gli utenti abbiano schermi ad alta definizione dove le finestre di Portento si vedono piccole.

Purtroppo non è possibile aumentare la dimensione del font, poichè si avrebbe l'effetto del testo che va a sovrascrivere gli elementi adiacenti.

L'unica cosa che possiamo fare, ma è una modifica piuttosto pesante, è:
- cambiare in Portento il font `sistema` da `Segoe UI,11` a `Segoe UI,15`
- riaggiustare col mask tutte le finestre (ma proprio tutte).

**Comment by mariocarmelo** [comment]
E... dopo questo lavoraccio avremo il risultato che le maschere di Portento non si potranno usare sui portatili da 10 o 12 pollici che ora si vendono ancora di più come IPad Apple e Surface di Microsoft dimostrano. Il "lavoraccio" al contrario era stato fatto per adattare tutte le maschere per quel tipo di monitor.
