### ISSUE TITLE
Fattura elettronica PA

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#14]
Da che parte sta?

**Comment by nippur72** [comment]
suppongo sia nel computer locale di @studioReggio

**Comment by mariocarmelo** [comment]
Infatti. Avendo notato che non è stato aperto alcun "ticket sul tracker" la mia domanda era appunto se era lì in novena, quarantena o esilio permanente?

**Comment by studioReggio** [comment]
Ho provato la fattura elettronica per fatture con aliquote diverse ed esenti. Il collaudo sul sito è riuscito. Ora vorrei che qualcuno la provasse su archivi reali. 
Tenete conto che si deve trovare una soluzione per inserire automat. i campi "progressivo invio" e "Codice Fiscale" nel riquadro dei Dati Trasmissione , perchè è antipatico digitarli tutte le volte. 
NB il controllo sul sito è  
http://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/AccediAlServizioAction.do?pagina=controlla_fattura

**Comment by studioReggio** [comment]
E' passato ormai parecchio tempo da quando ho aggiornato i clienti della fatturazione elettronica funzionante e non ho ricevuto più nessuna comunicazione di errore. Vuoi pechè non ce ne sono, vuoi perchè forse i clienti hanno provveduto diversamente, ritengo di poter chiudere il ticket .
