### ISSUE TITLE
Portento è compatibile con Windows 10 ?

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#142]
I clienti che stanno per installare la versione 10 di Windows ne vogliono essere certi.

**Comment by nippur72** [comment]
per quello che so, non ci dovrebbero essere problemi, in quanto tutto ciò che gira su Vista, 7, 8.x gira anche su 10.

**Comment by mariocarmelo** [comment]
Ho installato Windows 10 sul mio portatile. L'unico problema che ho notato finora riguardo Portento sembra essere una imperfetta visualizzazione della finestra di documentimagazzino che si presenta "leggermente schiacciata" a destra e sotto. Windows 10 sembra gestire diversamente le ampiezze di riga colonna forse quando viene definito un minimo e maxi pixel almeno nei valori predefiniti in documentimagazzino.
