### ISSUE TITLE
Acquisizione da causale (rev.2.03) :la  scelta da F6 non funziona dopo la prima volta 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#144]
Il cliente Polimeno ha segnalato che in acquisizione da causale, la prima volta che si sceglie una causale (con F6) va tutto bene. 
La seconda volta, appena si dà F6 per scegliere una nuova causale dà questo messaggio : 
Objet reference not set to an instance of an object 
Ho circoscritto l'errore nella funzione PopolaAlbero() , ma non con tutti i database si evidenzia il problema, per cui potrebbe essere anche un problema di archivio delle causali  
NB ho il DB del cliente per eventuali prove.

**Comment by nippur72** [comment]
numero di linea dove si verifica l'errore?

**Comment by studioReggio** [comment]
non è un errore di Portento (col papero) ma di framework , provo a mandartelo altrimenti sul desk del server c'è il file.word Acquimov errore 
Se hai bisogno di vedere il difetto chiamami ti collego con DB in questione. 

[acquimov errore.docx](https://github.com/nippur72/issuep/files/6621/acquimov.errore.docx)

**Comment by nippur72** [comment]
non riesco a riprodurre l'errore in maniera ripetibile, sembra sia un mix di eventi dell'albero che fanno a pugni. 

Comunque ho modificato leggermente la gestione dell'albero in `acquimov.pc` (peraltro molto vecchia) in modo tale che l'albero non venga rigenerato ogni volta ma solo all'inizio. 

In questo modo si recupera anche il posizionamento della causale corrente sull'albero che non funzionava nemmeno.

**Comment by studioReggio** [comment]
Il difetto persiste - per evidenziarlo utilizzare il DB del cliente acquisendo da causale, selezionando la prima volta una causale e la seconda volta un'altra (oppure chiama ti collego con il mio pc )

**Comment by studioReggio** [comment]
Il cliente telefona in continuazione per segnalare il problema, non si riesce a lavorare cambiando la causale di inserimento. Quando hai un attimo collegati con il mio PC

**Comment by nippur72** [comment]
Ho modificato nuovamente la gestione dell'albero in `acquimov.pc` per aggirare l'ostacolo. Ho fatto delle verifiche e sembra funzionare, puoi confermare?

**Comment by studioReggio** [comment]
Confermo, collaudo OK, ho cambiato la revisione ed è su Stage . Aspetto due gg prima di renderlo uffciale su Net Working, e quindi rilasciabile.
