### ISSUE TITLE
Menu di contabilità - voci non utilizzate - dimensioni maschera più grande? 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#147]
Nel menu di contabilità ci sono alcune voci relativi a moduli che non esistono.  Valutare se hanno ancora motivo di esistere ed eventualmente fare pulizia: 
da BILANCI : Importazione dati 
da MODULI UTILITA : totali registri  - registro unico - Riepilogo scritture settoriali - prelevamento movimenti 
da MODULI DI SERVIZIO : verifica movimenti iva semplificata 

INOLTRE: si può allargare un po la maschera del menu?

**Comment by nippur72** [comment]
Con il nuovo gestore il menu si allarga automaticamente quando ci sono elementi dell'albero che sono troppo grandi.
