### ISSUE TITLE
Aumento globale del timeout 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#155]
Per ripetuti messaggi di errore di timeout riscontrati dai clienti durante l'apertura di programmi (es. desktop) , è possibile alzare il timeout globale del Gestore oltre i 15 ''  ? Oppure passarglielo come parametro  es. dal .DSN?

**Comment by nippur72** [comment]
Basta aggiungere nel DSN il parametro `Timeout`, ad esempio:

```
Server=localhost\SQLEXPRESS;Database=Portento;User Id=sa;Password=sa;Timeout=200
```

Nella stringa di connessione si possono passare altri parametri, vedere [Stringa di connessione](https://msdn.microsoft.com/it-it/library/system.data.sqlclient.sqlconnection.connectionstring%28v=vs.110%29.aspx).
