### ISSUE TITLE
Articoli.pc campo MovUnivocoSiNo non trovato

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#16]
ho un normale database v51, quando apro articoli mi da un'errore non gestito, non trova il campo `MovUnivocoSiNo`.

Ho guardato il grande creatore e c'è un riferimento sotto commento ad una fantomatica versione 52.

Il solito pasticcio che mi sta facendo perdere un sacco di tempo.

**Comment by mariocarmelo** [comment]
Questa sinceramente non l'ho proprio capita!  Articoli ha da tempo immemore un campo che si chiama MovUnivocoSiNo. Nel grande creatore (attuale) è infatti (ancora) un campo binario della tabella articoli  posizione n-10.
Poi esiste un normale commento a scopo evidente di  promemoria nella  region posizione_per_nuovo_Aggiornamento  in cui è scritto: // per la revisione (52). 
// rinominare in articoli MovUnivocoSiNo in FlagStampaCartellini.
Questo mi è chiaro, tutto il resto non lo capisco.

**Comment by nippur72** [comment]
neanch'io lo capisco, fatto sta che mi ritrovo a lavorare con un database che ha questa modifica. 

Sentiamo anche @studioReggio e poi chiudo.

**Comment by mariocarmelo** [comment]
Confronta la tabella articoli del tu DB con articoli del GC per il campo MovUnivocoSiNo posizione n-10
e fammi sapere,

**Comment by nippur72** [comment]
questo è quello che viene fuori dal confronto:

```
Campo                           mio db      db del grande creatore
================================================================
Mag_Articoli.FlagStampaEti      bit(1)      non esiste  
Mag_Articoli.Posizione          non esiste  varchar(8) NOT NULL 
Mag_Articoli.MovUnivocoSiNo     non esiste  bit(1)  
Mag_Articoli.TipoRicarico       non esiste  tinyint(3) NOT NULL 
Mag_Categorie.CodiceAgenteRete1 non esiste  varchar(5)  
Mag_Categorie.ProvvAgenteRete1  non esiste  real(24)    
```

**Comment by mariocarmelo** [comment]
E sarebbe la Rev. 51?  Il problema è uno ed uno soltanto: mi incazzo troppo poco è troppo poco spesso. Per risolvere questo problema ci vorrebbe un incazzamento al secondo ma senza certezza alcuna di risultato. Comunque sai come avevo risolto il problema già nel lontanissimo 1978-79? Con la progenitrice di Silvia. Il computer era una elettromeccanica Olivetti Audit 5. La collaboratrice tale carissima ed ancora testimone Teresa Macrì. Prime "procedure" scritte dal sottoscritto in assembler su schede elettromagnetiche. Ogni programma effettuava il controllo sulle incongruenze o volgarmente "cazzate" della signorina. Al terzo errore emetteva il tranciante messaggio: "è' la terza stupidaggine che fai oggi. Con te io non lavoro." È la elettromeccanica si autospegneva. Ora vedrai cosa farà la nipote.

**Comment by nippur72** [comment]
Non lo sapremo mai.
