### ISSUE TITLE
Silvia.pc

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#17]
Ho creato un modulo `Silvia.pc` che svolge la funzione di pronunciare il testo utilizzando `DSpeech.exe`, evitando la duplicazione del codice.

Il modulo potrebbe implementare i comandi tipo `<EMPH>` di dspeech, facilitando la scrittura del codice "che parla".

Esempio di utilizzo:

``` C#
// crea l'oggetto Silvia
Speaker Silvia = new Speaker(); 

Silvia.Testo("Ciao");
Silvia.Silenzio(300);
Silvia.Testo("Come stai?");
Silvia.Parla();
```

**Comment by mariocarmelo** [comment]
Suggerisco di attivarlo subito in DocumentiMagazzino giacché  è appunto in modifica ed avevo iniziato a predisporlo alla sintesi vocale ed I.A. Ultima region del modulo.

**Comment by nippur72** [comment]
Si, è già attivo in `DocumentiMagazzino.pc` (in stage).

**Comment by nippur72** [comment]
chiuso per nessuna risposta pervenuta in tempo utile.
