### ISSUE TITLE
dalle browse di ricerca - stampa browse - non stampa il codice anagrafico 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#177]
In tutte le browse di ricerca dove c'è il codice anagrafico , se si sceglie di stampare la browse , questo codice viene stampato a  zero.
Es. vedi browse di ricerca clienti, fornitori, ecc.

**Comment by nippur72** [comment]
l'errore è dovuto a browser scritte male:

```
      Formati = "000000||||||||";
```

si pretende di formattare il codice come se fosse numerico (`000000`) ma in realtà `CodAnagrafica` è una stringa.
