### ISSUE TITLE
campi in memoria e su DB - metodo di registrazione 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#178]
Ho un dubbio che vorrei chiarirmi: 
C'è  differenza ad assegnare valori a campi in input collegati al DB, piuttosto che direttamente campi del DB? 
se esempio assegno un valore ad un campo  CInputDescr.Valore = "aaaa" 
e il campo è collegato ad un campo del DB ,  
devo o no fare il Post della tabella corrispondente?
Se invece assegno un valore direttamente al campo su tabella 
es. Tabmag_Clienti.Descr = "aaaa"
perchè devo fare il post?
Quando si fanno assegnazioni  è meglio utilizzare la prima o la seconda tipologia di nome campi?

**Comment by nippur72** [comment]
è sempre preferibile scrivere nell'oggetto `Tabella`, per una questione di chiarezza.

Sul perchè si deve fare il `Post()`, il motivo è per minimizzare gli accessi al DB:

``` C#
tab.Campo1 = 1;
tab.Campo2 = 2;
tab.Campo3 = 3;
tab.Post(); // fa una sola scrittura sul DB
```
