### ISSUE TITLE
Modifiche al gestore

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#19]
Ho trovato su setup  di discorete il gestore modificato del 27/04. Occorre anche per il gestore seguire le procedure che stiamo ora utilizzando a valere su tutto il materiale di Portento: .pc,md,mrt,ecc. In questo modo abbiamo tutti contezza dei motivi e dell'entità delle modifiche correttamente seguite dai relativi test.

**Comment by nippur72** [comment]
Quello che dici è già stato fatto, probabilmente ti sei perso #3 e #9
