### ISSUE TITLE
DocumentiMagazzino.pc

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#2]
Revisione di documenti magazzino (già discusso via email)

**Comment by mariocarmelo** [comment]
È' indispensabile la verifica delle modifiche ma ora il gestore #36 non lo consente per errore: "Metodo statico Library.Split(+String.String) non supportato in RunMethodStatic.

**Comment by nippur72** [comment]
usa #39

**Comment by mariocarmelo** [comment]
Ho iniziato le verifiche. alcune modifiche già apportate al modulo.

**Comment by mariocarmelo** [comment]
Per evidenze e promemoria vedi #47.
DocumentiMagazzino. ValorePredefinito c'è qualcosa che non va "nell'impostazione predefinita" in fattura sembra funzionare nel DDT No. (forse si dovrebbe controllare congiuntamente in tre?)

**Comment by mariocarmelo** [comment]
7042 // TODO(nino) qualcuno può documentare che cosa è/fa flag?
VEDI COMMENTO A SEGUIRE NEL MODULO.

**Comment by mariocarmelo** [comment]
Adeguato al nuovo Moduli_Revisione. N.B. nr_modulo resta variabile globale!

**Comment by nippur72** [comment]
Ho sistemato alcune cose in `ImpostaPulsanti()`, fra cui il fatto che i pulsanti si disabilitano correttamente quando il record è su eof.

**Comment by nippur72** [comment]
Riguardo ImpostaPulsanti(), come esempio notate come il pulsante "scadenze" rimane inattivo quando il documento è un DDT (non sono previste scadenze).
