### ISSUE TITLE
Riunificazione DocMag + Margini

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#22]
Ho riunificato `MarginiDocumenti.pc` con `DocumentiMagazzino.pc`, adesso premendo `F5` sul totale documento si apre una finestrella dove si vedono i margini calcolati, in più il corpo e il piede si modificano per visualizzare le colonne di "costo" e "ricarico".

Il pulsante "Nascondi Margini" posto sulla stessa finestrella permette di ritornare al normale documenti di magazzino.

Non ho usato nessuna DLL o stratagemma vario, è una semplice finestra.

Per semplificare le cose, adesso DocMag si comporta sempre come se fosse "margini", cioè include sempre il campo del costo e calcola il ricarico anche se il campo è nascosto.

Se questa modifica va bene si può definitivamente cancellare `MarginiDocumenti.pc`.

**Comment by mariocarmelo** [comment]
Attenzione la griglia di margini non permette di modificare il campo del costo. Questo deve ovviamente  potersi modificare ma anche con F5 visualizzare il relativo campo "costo ultimo" di articoli che documenti di magazzino usa per valorizzare in MovMag "CostoAcquisto".

**Comment by mariocarmelo** [comment]
Ho apportato modifiche alla "finestrella" di riepilogo dei costi giusto per completezza e far risparmiare tempo. Non garantisco solo circa le variabili di assegnazione che ho utilizzato per i campi aggiunti: Totale merci e Totale IVA ma  mi interessava il concetto. Spero renda maggiormente l'idea della funzione e di conseguenza l'assegnazione esatta dei relativi  valori e percentuali.
Attenzione che se la "finestrella" si chiude da X non cambia la finestra principale che resta configurata su margini.

**Comment by nippur72** [comment]
la colonna costo è `readonly` perchè così era nel vecchio margini:

``` C#
// omaggio                             cod    descr  Um    Iva   conf   qta    prz    sc     impo   costo ric.
GrigliaCorpo.SetRow(riga,"readonly", [ false, false,  true, false, false, false, false, true, true, true, true ] );      
```

Ho sistemato i campi che hai aggiunto.

Se si chiude con "X" è giusto che margini resti impostato, è l'unico modo per poter lavorare sul documento visto che la finestra è aperta con `ShowDialog()`. Se si vuole chiudere la modalità "margini", basta riaprire la finestrella e premere il pulsante "nascondi".

**Comment by studioReggio** [comment]
Col dottore abbiamo stabilito che il costo in movmag visualizzato in margini deve essere modificabile , senza naturalmente toccare articoli, e deve prevedere l'F5 per entrare in Articoli, Foglio Prezzi .

**Comment by nippur72** [comment]
Ho sistemato il tasto `F5` in margini, mi potreste controllare soltanto i tipi articolo dove deve essere `readonly` ?

**Comment by studioReggio** [comment]
Nel provare stamattina margini ho notato: 
- se cambio il costo di un articolo non scattano i ricalcoli nè al corpo nè aggiorna il tot.costi in finestra    margini
- non viene evidenziato il margine per Sconti Merce 
- non scatta la % di margine per trasporto e contratto 
  per quanto riguarda il tasto F5 sul costo deve essere R/O per tutto quello che non pesca in articoli, cioè : art.manuale (tipo 4) , spese (tipo 5)  e descr.aggiuntiva (tipo 6) 
  Forse il modo showdialog di aprire margini induce in errore se io cambio per qualsiasi motivo documento. Infatti non ho più la certezza che la finestra margini appartiene al doc.sottostante fino a quando non chiudo e nascondo, e poi riapro.

**Comment by nippur72** [comment]
riguardo all'ultimo punto, mancava il rinfresco delle finestrelle nella `_Moved()` che ho sistemato

**Comment by mariocarmelo** [comment]
Il costo deve essere R/O solo nelle descrizioni aggiuntive per l'avvio motivo che non vi è prezzo e quindi nemmeno un costo. Gli articoli manuali e le spese avendo un importo va sempre indicato il costo relativo altrimenti viene falsato il margine.

**Comment by mariocarmelo** [comment]
Come già segnalato da Rosalba (vedi sopra) non scattano i ricalcoli dei costi e del margine se inserisco spese di trasporto nelle mini-finestra o nella principale, Come non ricalcola se vario il costo di uno o più articoli.

**Comment by nippur72** [comment]
Ho sistemato anche questi, più altri piccoli refusi. 

I campi di margini che non si possono modificare li ho messi a sfondo grigio (`Control`).

**Comment by mariocarmelo** [comment]
Tuto ok. Questo lavoro può considerarsi completato.
