### ISSUE TITLE
Stampa allegati in fattura 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#24]
Nel passaggio dalla rev. 48 alla rev. 49 dal D.B. relativa tra l'altro alla eliminazione del campo Allegato dai moduli, non era stato modificato il modulo DocumentiMagazzinoStampa.PC che leggeva ancora da movmag.  
Tutti gli altri moduli sono a posto, per cui immagino che sia stato  "saltato"  questo per svista.
La variazione è su stage. 
Evidentemente i clienti non usano (più) stampe di allegati da documenti di magazzino altrimenti l'avrebbero segnalato.

**Comment by nippur72** [comment]
per me ok :+1:

**Comment by studioReggio** [comment]
passo il .PC in portento.net working
