### ISSUE TITLE
Uso di QuantitaInEvasione e QuantitaEvasa in DocMag?

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#27]
La griglia di DocMag apre `QuantitaInEvasione` e `QuantitaEvasa` ma non riesco a trovare dove vengono usati poi questi campi. Non sono visibili e nessuno ci scrive dentro.

Sono una ridondanza / residuo di vecchio codice ?

**Comment by studioReggio** [comment]
No, questi due campi vengono usati nella gestione degli ordini clienti e fornitori. Pilotano infatti l'evasione parziale/totale degli ordini , i solleciti, le disdette , insieme al valore che assume il campo TipOpeParticolare in Comovditte. (vedi spuntaordiniFornitori.pc). Inoltre concorrono alla ricostruzione delle quantità ordinate/impegnate in Articoli e Servmag.

**Comment by studioReggio** [comment]
Per quanto riguarda Documenti di magazzino sono utilizzate in AumentaQuantitaMagazzino(segno), e in elimina_documento . 
Piuttosto , l'istruzione 
"UPDATE Mag_Articoli SET QSpedizione = QSpedizione - {0:SN} WHERE Id={1:SN}", 
alla riga 3174 toglie da qspedizione di Articoli una quantità che mi sembra non sommi da nessuna parte.
