### ISSUE TITLE
Acquimov - Browse di ricerca - la ricerca specifica non funziona per alcune colonne  

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#28]
In acquisizione, nella browse di ricerca, se si utilizza il menu a tendina "Dove - in tutti i campi", 
e si sceglie di ricercare nei campi: 
Registro,  Tipo, Codice o Citta 
dà errore: "il nome di colonna (nomecampo) non è valido. 
Per la data di registrazione funziona solo se ricerco una data completa nel formato gg/mm/aaaa .

**Comment by nippur72** [comment]
Ho riscritto la parte del "filtro" del componente `Browser`, adesso:
- non da errore se la ricerca è fatta su un campo che è frutto di un calcolo (caso di cui sopra)
- è possibile effettuare la ricerca in campi di raggruppamento (`SUM`, `COUNT`) mentre prima invece li saltava
