### ISSUE TITLE
Creare Vista_ListiniCorrenti per evitare in stampe listini la duplicazione degli articoli   

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#30]
Le stampe listini hanno rilevato un effetto collaterale dovuto ai listini storici che trova in Mag_listini,  cioè , 
se scelgo listino da stampare 1 
vengono stampati gli articoli tante volte quanti sono i listini n.1, con il prezzo 1 più recente.
La costruzione della SELECT infatti riesce a leggere il prezzo 1 più recente : 

SELECT A.Id,CodiceArticolo,.....(SELECT TOP 1 Prezzo FROM mag_listini Where idarticolo = A.id AND numerolistino=1 ORDER BY DataVariazionePrezzo Desc) as Prezzo1, ....... 

ma il  WHERE risulta 
.... WHERE A.IdDitta=1 AND A.IdMag=1 ... AND C.ProgressivoIns = 1  AND L.numerolistino=1 

per cui stampa tutti i numerolistino=1 di ogni articolo. 
Nino ha già affrontato il problema con me, occorre ora modificare il Grande Creatore.

**Comment by nippur72** [comment]
una vista in più non fa male a nessuno, quindi direi che la puoi creare senza problemi.

**Comment by nippur72** [comment]
Ho creato la vista `Vista_Listini_Correnti` che riporto qui di seguito:

``` C#
DB.Execute(@"CREATE VIEW Vista_Listini_Correnti AS
                WITH Prequery AS 
                (
                   SELECT IdArticolo,NumeroListino, MAX(DataVariazionePrezzo) AS Data 
                   FROM [Mag_Listini]
                   GROUP BY IdArticolo,NumeroListino
                )
                SELECT L.* FROM Mag_Listini L 
                LEFT JOIN Prequery P 
                     ON L.IdArticolo = P.IdArticolo 
                        AND L.NumeroListino = P.NumeroListino 
                        AND L.DataVariazionePrezzo = P.Data
                WHERE P.Data IS NOT NULL"); 
```
