### ISSUE TITLE
Nuove Split e Join

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#34]
Ho fatto la seguente modifica al linguaggio:
- `Split` e `Join` si possono chiamare solo come metodi del tipo `Variant`, la vecchia sintassi a funzione non è più supportata.
- ho adeguato i sorgenti attuali (in stage)
- ho aggiornato le relative pagine del manuale.

**Comment by mariocarmelo** [comment]
Questa modifica crea solo complicazioni. Non avvertivamo alcuna urgenza o necessità. SOPRATTUTTO NON ANDAVA FATTA IN QUESTO MOMENTO. Ora il gestore semplicemente è stato reso incompatibile in avanti ed a ritroso. Per poterlo utilizzare in reale si dovranno attendere "TUTTE" le modifiche in corso su stage fino alla conclusione dei loro test che per quel riguarda documenti di magazzino saranno complessi e certamente non si risolveranno in un giorno. Per giunta la modifica il gestore al momento neppure la gestisce in ambiente di sviluppo e quindi oggi non consente nemmeno  i test dei moduli per cui siamo completamente immobilizzati.

**Comment by nippur72** [comment]
- la modifica mi serve per documenti magazzino, quindi era necessaria.
- non capisco il concetto di "incompatibile in avanti"
- la modifica di `Split` e `Join` è una normale operazione di [Refactoring](http://it.wikipedia.org/wiki/Refactoring), non vedo tutta questa catastrofe. Comunque per evitare questioni, ho ripristinato _anche_ la vecchia sintassi, vedi #39
