### ISSUE TITLE
Gestore 8/5 non funzionano più le ricerche nelle Browser 

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#38]
Non so da quando è cosa sia successo comunque nessuna ricerca selettiva è ora consentita da una browser che sembra accettare solo il tasto invio. L'ultima discussione sull'argomento era stata la #28 tra l'altro chiusa velocemente e non so in base a quali verifiche.

**Comment by nippur72** [comment]
a causa di un conflitto tra il filtro della browse (fatto con l'istruzione `WITH`) e la clausola `ORDER BY`, sono stato costretto a ripristinare la vecchia versione parzialmente funzionante della browse.
