### ISSUE TITLE
Moduli_Revisioni.pc

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#4]
Revisione di `Moduli_Revisioni.pc` (già discusso per email)

**Comment by mariocarmelo** [comment]
L'attuale versione del controllo della revisione collega al mancato superamento della verifica sul database un errore bloccante (Controllo_Revisione = false) mentre visualizza una messagebox di semplice avviso qualora rileva discordanza nella versione del modulo in esecuzione che comunque può essere eseguito.
Nella modifica apportata l'errore è sempre bloccante per qualsiasi test non superato. 
Corretto un errore nel messaggio visualizzato - TODO (Mario).

**Comment by nippur72** [comment]
ok, adesso se la revisione è diversa da quella del menù l'errore non è bloccante.

**Comment by mariocarmelo** [comment]
Passo la revisione in net working e chiudo l'argomento.
