### ISSUE TITLE
La chiave specificata non era presente nel dizionario

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#40]
Nel modulo 'Desktop' alla funzione FinestraDesktop_Mostrata() alla linea 643!!!
Se non si migliora il messaggio o i controlli quando un modulo chiama tante dll capire cosa esattamente non trovi sará impresa non da poco.

**Comment by nippur72** [comment]
L'errore è sparito rigenerando la dll, comunque ne ho approfittato per rendere più descrittivo il messaggio di errore.

C'è da dire inoltre che #41
