### ISSUE TITLE
Codifiche diverse da UTF8

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#43]
Occorre prevedere la possibilità nel leggere o scrivere file di testo,CSV di selezionare anche via software la codifica che si desidera o si deve usare per lo specifico file: in particolare l'ASCII standard e l'ANSI Windows.

**Comment by nippur72** [comment]
Ho aggiunto la proprietà `Codifica` nel componente `File` per gestire i vari tipi di codifiche. 

Per default è `UTF8`. Vi rimando alla pagina di Help di `File`che ho sistemato.

Un esempio:

``` C#
File f2 = new File("miofileascii.txt"); 
f2.Codifica = "ASCII"; 
f2.ApriAppend();  
f2.WriteLine("Oggi è un giorno fortunato, hai vinto 12 €"); // essendo ascii, "è" e "€" non vengono codificati bene
f2.Chiudi();
```

**Comment by mariocarmelo** [comment]
C'è nell'esempio sul file MD una piccola svista: è scritto f = new File anziché f2 = new File. Un'inezia che avrei voluto correggere giusto per iniziare a lavorare sugli Help. Ho rinunciato perchè ben più dell'ago nel pagliaio.
