### ISSUE TITLE
adeguamento Stampe di Magazzino alla nuova vista listini_correnti 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#45]
E' stata inserita la gestione della vista_listini_correnti nel programma di stampa ArticoliStampe.PC . 
Se riesce qualcuno a collaudarlo , anche nel contesto generale, lo passo in net working

**Comment by mariocarmelo** [comment]
Il programma sembra funzionare sia per quanto riguarda il listino completo che quello ridotto.
Mentre continuo il test che completerò oggi segnalo che la data di stampa non deve essere esclusivamente quella del giorno pertanto questa va proposta in apposita finestra per dare allo operatore la possibilità di variarla.

**Comment by mariocarmelo** [comment]
Ok i listini sia ridotto che completo visualizzano correttamente i relativi prezzi.
Due appunti.
1 - visto che la modifica presuppone la generazione della nuova vista dal grande creatore è utile contestualmente prevedere la rev. 52 del DB con le modifiche in promemoria. In questo modo si ha pure l'opportunità del controllo automatico dell'aggiornamento ponendo in articolistampe 2.05 anche versione_database = 52,
2 . Prima del rilascio occorre controllare i Totali visualizzati da listino completo e ridotto sul pannello della finestra visualizzata perché non sono coerenti con il numero di articoli e delle pagine effettivamente generate e stampate.

**Comment by mariocarmelo** [comment]
Sbaglia ancora nei Totali visualizzati l'indicazione del numero delle pagine del report. Il numero di articoli è Ok.
L'ho adeguato al nuovo Moduli_Revisione.

**Comment by studioReggio** [comment]
inserita data di stampa - prove stampa ok - passato a net working

**Comment by studioReggio** [comment]
PS il numero di pagine del report nei totali è indicativo ma non preciso perchè ogni tabulato ha un numero diverso di righe per ogni pagina, a causa della presenza o meno dell'intestazione gruppo, totali, doppie righe per articolo... Si dovrebbero censire tutti i tabulati e assegnare ad ognuno il suo numero di righe, ma penso che non ne valga la pena.
