### ISSUE TITLE
EvidenzePromemo.pc 

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#47]
Ho dato una prima sistemata alla gestione delle evidenze e dei promemoria in DocMag, adesso `EvidenzePromemo.pc` ospita la classe `Evidenze` utilizzabile come DLL.

Non sono entrato nei dettagli dell'implementazione, mi sono limitato a compattare il codice e a renderlo più snello.

Esempio di uso:

``` C#
// crea oggetto evidenze passando il nr modulo
Evidenze EvidenzaArticolo     = new Evidenze(3104);  
Evidenze EvidenzaFornitore    = new Evidenze(3107);  
Evidenze EvidenzaCliente      = new Evidenze(3106);
Evidenze EvidenzaIntestatario = new Evidenze(1);
Evidenze EvidenzaDestinatario = new Evidenze(1);
Evidenze EvidenzaDocumento    = new Evidenze(nr_modulo); 

// mostra evidenza e promemoria passando l'id
EvidenzaDocumento.MostraEvidenza(id_modulo);
EvidenzaDocumento.MostraPromemoria(id_modulo);

// aiuta ad impostare i pulsanti
var evi = EvidenzaDocumento.HaEvidenza(id_modulo);
PulsanteEvidenza.Testo   = evi ? "Evidenziato"   : "Nessuna evidenza";

   // gestione del pulsante evidenza
   if(!EvidenzaDocumento.HaEvidenza(id_modulo))
   {
      var risp = MessageBox("avviso","Mettere il documento in evidenza?","sino");
      if(!risp) return;
   }   
   EvidenzaDocumento.CreaEvidenza(id_modulo);
```

**Comment by mariocarmelo** [comment]
Ok ma non visualizza il messaggio della memo quando si digita il relativo tasto: evidenza, promemoria.
Comunque risulta regolarmente memorizzato.

**Comment by nippur72** [comment]
In realtà c'era un errore, duplicava il record. Ora ho sistemato.

**Comment by mariocarmelo** [comment]
I moduli non devono essere visualizzati quando si richiamano le mini-finestre di provvigione e margini come ora erroneamente succede.

**Comment by nippur72** [comment]
quali moduli?

**Comment by mariocarmelo** [comment]
Nino se generi una evidenza o un promemoria in documenti di magazzino la loro visualizzazione ti viene proposta correttamente nell'accedere al documento. L'errore sta che quando, dallo stesso documento, chiami margini o provvigioni ti ripropone nuovamente l'evidenza o il promemoria o entrambi se sono previsti. Questo ovviamente ripetutamente ogni volta che premi il tasto provvigioni o selezioni margini. Ovviamente evidenza e promemoria non devono essere visualizzate in margini o provvigioni e per nessuna altra selezione nel documento visualizzato.

**Comment by nippur72** [comment]
Ok, ora ho capito. 

Per sistemarlo anzichè chiamare la `Moved()` adesso chiamo solo il pezzo che ricostruisce il corpo fattura, il che dovrebbe anche velocizzare un pò.

**Comment by mariocarmelo** [comment]
Tutto OK. E'  in corso l'adozione della DLL in tutti i moduli che la prevedono.
