### ISSUE TITLE
Rev. 52 DB

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#48]
per la revisione (52):
   // rinominare in articoli MovUnivocoSiNo in FlagStampaCartellini (riutilizzato)  
   // cambiare i char(8) in varchar(8) di Codintestatario e codvettore delle categorie - non si gestisce la lettura della relativa ragione sociale (?)  (TODO nome???)

**Comment by studioReggio** [comment]
ho modificato il grande creatore per la rev. 52, ed ho modificato la variabile MovunivocoSiNo  nei programmi interessati tranne ArticoliStampe , dove ho trovato delle inesattezze. 
Inoltre bisognerà riguardare le categorie per l'assegnazione al campo "RagioneSociale"

**Comment by studioReggio** [comment]
Domani conto di finire ArticoliStampe che avevano un difetto sulla data limite di stampa e i contatori della finestra errati.

**Comment by studioReggio** [comment]
Articoli stampe è finito - comprende tra l'altro anche l'inserimento di un nuovo tabulato che stampa il listino ridotto con provvigioni intestato per fornitore o settore. Passato su Stage

**Comment by nippur72** [comment]
@studioReggio visto che hai modificato il numero di versione, dovresti adottare il nuovo `Moduli_Revisione`.

**Comment by mariocarmelo** [comment]
Ok va tutto bene. Ho inserito Moduli_Revisione.

**Comment by mariocarmelo** [comment]
Ok anche per Articoli.pc rev 2.09 inserita Moduli_Revisione

**Comment by mariocarmelo** [comment]
Tutto Ok l'adozione della DLL Moduli_Revisione è in corso per tutti i moduli.
