### ISSUE TITLE
Audio.pc

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#52]
Similmente a quanto fatto per evidenze e promemoria, ho esternalizzato in una DLL la parte di docmag che gestisce le note vocali. 

Si trova in `Audio.pc`.

**Comment by nippur72** [comment]
Piccolo aggiornamento: ho adattato `audio.pc` e docMag a #54, poiché non c'è più bisogno di gestire la cancellazione del file audio da programma.

**Comment by mariocarmelo** [comment]
Ok la nuova versione funziona correttamente e si è iniziata l'adozione della DLL in tutti i moduli che la prevedono.
