### ISSUE TITLE
Moduli_Revisioni.pc 

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#57]
var nr_modulo = versione["modulo"].ToString() alla 29 dovrebbe essere ToInt 
altrimenti
// [NON] formatta per bene nr_modulo secondo il menu
57   nr_modulo = Format("{0:0000}",nr_modulo);
nr_modulo Anagrafe = 1 -> ToString = "1" -> Format("{0:0000}" = "1" invece di "0001"

**Comment by nippur72** [comment]
si ci va `ToInt()`.

fuori argomento: quando scrivi qui poi usare la sintassi markdown per evidenziare il codice, con il carattere dell'apice trasverso (`) es:

``` C#
// [NON] formatta per bene nr_modulo secondo il menu
57 nr_modulo = Format("{0:0000}",nr_modulo);
nr_modulo Anagrafe = 1 -> ToString = "1" -> Format("{0:0000}" = "1" invece di "0001"
```

**Comment by mariocarmelo** [comment]
` prova inserimento

**Comment by nippur72** [comment]
Riapro il ticket solo per dire che a questo punto l'intestazione del tipo:

```
//<Modulo.nome = "EvidenzePromemo" - data_ultima_modifica = "08/02/2014" />
```

è secondo me ridondante (volendo il nome lo si può aggiungere all mappa passata a `Revisione()`):

```
//Revisione rev = new Revisione({ modulo: nr_modulo, versione: 2.01, database: 50, data: "20/05/2015", nome="EvidenzePromemo" });
```

**Comment by mariocarmelo** [comment]
La data certamente andava tolta, è stata una svista. Lo standard infatti si può vedere in: Anagrafe,Brogliaccio,Articoli. Tutti moduli aggiornati che stanno per passare in net working.
Il nome no. Meglio lasciarlo in testa appunto come intestazione in commento di ogni modulo, per come lo stesso sarà memorizzato e richiamato. Mi sembra molto pratico. La data è comoda sotto per evitare sali/scendi ad ogni modifica.

**Comment by nippur72** [comment]
a sto punto allora è meglio mettere:

```
var revisione = { nome: "..", versione: ... };
```

in cima al modulo (come prima linea) e poi usare la variabile `revisione` per fare i controlli nella mostrata:

```
Revisione rev = new Revisione(revisione);
```

**Comment by nippur72** [comment]
EDIT: in realta questa cosa non si può fare, poichè non si può mettere nessuna istruzione prima della parola `interfaccia`, però volendo si potrebbe modificare la sintassi.

**Comment by mariocarmelo** [comment]
Lascia perdere. Poi ti lamenti delle variabili globali. Addirittura modificheresti la sintassi per metterle oltre che dopo anche prima dell' interfaccia. E poi per cosa? Per un nome di commento che non serve a nessuno se non per ricordare all' interno il nome del modulo. Revisione assieme a versione_database in mostrata hanno anche il vantaggio di essere variabili locali anziché le globali di prima.

**Comment by mariocarmelo** [comment]
Perché non parliamo di cose serie? Ho notato con piacere che è attivo il backup automatico dei moduli modificati anche con il nuovo editor. L' aggiornamento mi è sfuggito o faceva parte dello scontato? Comunque occorre chiarire la funzionalità soprattutto con riferimento al tempo controllato.
Così come con il gestore di ieri è stato introdotto il controllo cartella. Nemmeno una parola di delucidazione. E' un aspetto a se stante o era il problema di EvidenzaPromemo?

**Comment by mariocarmelo** [comment]
Oramai è definitivo è per tutti definitivamente chiaro che // #region Riferimenti DLL
deve stare dopo le variabili globali in modo che si possa passare come parametro una variabile globale (es, nr_modulo).

**Comment by nippur72** [comment]
In ordine:
- quella di avere una variabile globale `versione` non era una cattiva idea, ci si poteva ad esempio risparmiare l'altra globale `nr_modulo` avendo al suo posto `versione.nr_modulo`. Comunque per me va bene anche così, visto che dopotutto non sono un grande fan dell'attuale controllo revisione. 
- se il _"commento non serve a nessuno se non per ricordare all' interno il nome del modulo"_, allora il commento andrebbe semplicemente tolto.
- il backup dei file dell'editor, insieme ad altre funzionalità, sono per ora instabili a causa del nuovo editor, ecco perchè sto omettendo di documentarle, ancora non so cosa ci sarà e cosa no.
- non ho capito che cosa intendi con "con il gestore di ieri è stato introdotto il controllo cartella" 
- riguardo a `#region DLL` in realtà il suo posto naturale sarebbe: `class`, `using` e `reference` in testa al modulo, mentre la dichiarazione degli oggetti-DLL dopo le globali. Per ora per semplicità le mettiamo insieme, ma dal punto di vista formale `reference` andrebbe in testa in quanto non si tratta nemmeno di una vera "istruzione", ma quella che viene detta in gergo viene detta [direttiva di compilazione](http://en.wikipedia.org/wiki/Directive_%28programming%29).

**Comment by mariocarmelo** [comment]
L'argomento si può riprendere nel futuro prossimo ora concentriamoci su problemi in corso più importanti: editor e help.
