### ISSUE TITLE
DocumentiMagazzinoStampa

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#60]
Il programma predispone la stampa degli allegati di articolo per poi chiedere con una TaskDialog:
"Stampare anche gli allegati degli articoli?".
Non tiene affatto conto che in articoli ogni allegato ha un flag per abilitare la stampa o meno:
StampaAllegato1. Questo "bug" compare ora per la prima volta nella stampa di un ordine a fornitore.

**Comment by mariocarmelo** [comment]
Per quanto sopra ho notato due errori nella StampaAllegati.
1 - LEFT JOIN Mag_Articoli A ON A.id = AL.Idmodulo AND A.StampaAllegato1=1
AND non funziona da filtro come avrà pensato chi lo ha messo.
2 - StampaAllegato1 è un duplicato parziale ed inutile di Comuni_Allegati.Stampa
quindi va tolto dalla tabella articoli mentre è corretto usare nella WHERE:
WHERE NrModulo=3104 AND M.idcomovditte= {0:SN} AND AL.Stampa=1";
Così funziona perfettamente.

**Comment by nippur72** [comment]
Si, effettivamente è così, la `LEFT JOIN` su articoli è inutile.
