### ISSUE TITLE
Eliminazione del flag StampaAllegato1 dai moduli 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#64]
Visto che si è deciso (giustamente) di togliere il flag dalla Tabella Articoli perchè inutile, vi suggerisco di rivedere soprattutto dal punto di vista del Grande Creatore nuova versione 53 lo stesso flag anche in : Agenti, Clienti, Fornitori e cespiti.

**Comment by mariocarmelo** [comment]
I seguenti moduli sono stati modificati ed il flag stampaallegato è stato tolto dalle relative tabelle (versione 53 BD): Cespiti,Articoli,Clienti,Fornitori,Agenti.

**Comment by mariocarmelo** [comment]
Per quanto riguarda modifiche e test l'argomento può considerarsi completato.
