### ISSUE TITLE
RiepilogoDDT.PC - errore di timeout

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#65]
Durante il riepilogo bolle si verifica errore di timeout - dai debug che ho messo si ferma alla riga 1178 di PartitaDoppia.PC  che sta su Stage (ho lasciato il debug) 
Per provare riepilogate la bolla del cliente n. 5

**Comment by nippur72** [comment]
mancava un

``` C#
PD.ImpostaDB(DB);
```

che appunto permette al modulo di partita doppia di usare lo stesso DB di riepilogo e quindi di usare la stessa transazione.

Quello che succedeva era che c'erano due transazioni, entrambe aspettavano che l'altra terminasse, cosa che non avveniva, da cui il timeout.

**Comment by mariocarmelo** [comment]
Riapro riepilogo DDT per promemoria di un altro problema: il documento riepilogato non genera eventuali scadenze.
Pongo il problema in questa issue visto che è in lavorazione  la gestione con DLL e quindi saranno contestualmente modificati  tutti i moduli interessati.
