### ISSUE TITLE
Distribuzione moduli rev. 52 del DataBase da Portento.NET Working 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#66]
Sto effettuando gli ultimi collaudi (soprattutto Documenti di Magazzino) per passarlo nella cartella   .NET Working e distribuire la release 52 del DB , prima che si faccia "troppo tardi", perciò non passate nulla in Working che non sia relativo a questa versione
Se c'è qualche problema che la Incal ha riscontrato nel frattempo fatemelo sapere. 
Appena stabilito che i programmi girano bene aggiorno a cominciare da Polimeno.

**Comment by mariocarmelo** [comment]
Occorre rilasciare la rev. DB 52 sempre con l'ultimo gestore disponibile comunque non inferiore al 22/05/2015

**Comment by mariocarmelo** [comment]
Si raccomanda di chiudere questo argomento prima possibile perché in stage i moduli che si stanno inserendo, a cominciare dal Grande Creatore,  sono tutti rev. DB 53.

**Comment by mariocarmelo** [comment]
Ho dato uno sguardo al .Net Working del Cedp e C.V.D. i "casini" ampiamente previsti e commentati con largo anticipo ci sono e come. Si sta ufficialmente rilasciando la rev DB 52 ed alcuni moduli sono chiaramente DB 53.
Vedi clienti  2.06 che contiene le modifiche "incomplete" del tipo provvigione che ovviamente essendo DB 53 non potranno in alcun modo funzionare. Idem Agenti 2.01. Mentre entrambi non hanno la modifica alla gestione dell'allegato (importante per chi ne fa uso) e che, a livello di maschera, è perfettamente compatibile con la rev. DB 52. Per non parlare di  evidenzepromemo.pc e suoni.pc che sono esattamente aggiornati ad oggi ed inseriti come DLL in DocumentiMagazzino 2.05 ed Anagrafe 2.02 tutti presenti sia in Stage che Net.Working ma nessuno ha mai chiuso i relativi test. Cosa altro devo aggiungere alle mie sollecitazioni, commenti, avvisi, raccomandazioni, preghiere, di sempre?

**Comment by mariocarmelo** [comment]
A seguito di quanto sopra definitivamente si precisa che tranne i seguenti moduli compatibili solo con la rev. DB 53:
- DB_Grande_creatore-pc  rev. 2.05
- Clienti,pc rev, 2.07
- Agenti.pc rev.2.02

TUTTI GLI ALTRI IN STAGE SONO RILASCIABILI PREVIO IL TEST D'USO PERCHE' COMUNQUE COMPATIBILI CON LA REV, DB 52.  
(ANCHE DocumentiMagazzino.pc rev, 2.05 NELLA VERSIONE AL 22/5/2015).
TASSATIVAMENTE: La revisione DB52 dovrà essere rilasciata con il gestore del 22/5/2015.

**Comment by mariocarmelo** [comment]
La versione DB53 sarà  immediatamente rilasciata ai clienti appena completata e testata la rev. 2.06 di DocumentiMagazzino con gli adattamenti in corso al DB53.

**Comment by studioReggio** [comment]
Se così deve essere, in conseguenza di cui sopra, allora ormai testiamo insieme Stage per la rev. 53 e poi passiamo tutto in Working per il collaudo finale prima della distribuzione , insieme al gestore del 22/05

**Comment by mariocarmelo** [comment]
C.V.D. I tempi per i clienti si allungano all'infinito perchè la rev. DB53 sará pesante ed il gestore non sará sicuramente più quello del 22/5. Non cambiando i convincimenti soggettivi, ciò che sta portando i clienti a "NON POTERE AVERE ALCUNA REVISIONE" questo è il dato di fatto sotto gli occhi e che dovrebbe portare ad un immediato ravvedimento, non vedo certo cambiamenti della situazione. Certo Il peggioramento. Ai clienti che segnalano qualsiasi problema, anche se risolto, non saremo in condizione di installarglielo. Vendiamo servizi ma se vendessimo pesci con le stesse modalità i clienti li mangerebbero sempre e solo putridi.

**Comment by studioReggio** [comment]
Rimando al #68
