### ISSUE TITLE
Documenti di Magazzino non elimina i documenti 

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#69]
L'ultima versione del programma ad oggi su Stage non cancella i documenti. Provare es. doc.9 -  10
Non è per caso collegata alle transazioni modificate di recente?

**Comment by nippur72** [comment]
c'era un abuso della variabile globale `id_modulo` che ho ridimensionato, adesso dovrebbe funzionare.

La modifica comporta che adesso c'è un unico punto in docmag dove viene impostata `id_modulo`, vale a dire nella `_Moved()`.

**Comment by mariocarmelo** [comment]
Ho riaperto perchè non potendo visualizzare le modifiche sul sorgente occorre precisare:
A - l'impostazione di id_modulo nella moved era già una regola fissa e credo debba essere stata rispettata per ogni modulo.
B - l'eccezione, in tutti i moduli, è costituita unicamente dall'id proveniente dall'esterno, attraverso CaricamentoAutomatico, appositamente per caricare un record specifico.

**Comment by nippur72** [comment]
riguardo a B): è inutile in quanto `id_modulo` viene impostato subito dopo, vale a dire:

``` C#
   PannelloDatiFissiStart();
   assegnazioni();              
   id_modulo = id;   // <- è inutile
   pagina = 1;
   bloccamessaggi=true;

   TabCoge_Comovditte.OpenKey([id]);   // perchè id_modulo viene imposto nella moved() che parte da qua
   CalcolaTotaliCorpo(); 
```
