### ISSUE TITLE
Desktop e PortentoMenuReader

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#7]
Da revisionare

**Comment by mariocarmelo** [comment]
L'attuale versione del controllo della revisione collega al mancato superamento della verifica sul database un errore bloccante (Controllo_Revisione = false) mentre visualizza una messagebox di semplice avviso qualora rileva discordanza nella versione del modulo in esecuzione che comunque può essere eseguito.
Nella modifica apportata l'errore è sempre bloccante per qualsiasi test non superato. 
Corretto un errore nel messaggio visualizzato - TODO (Mario).

**Comment by mariocarmelo** [comment]
Ora tutto Ok. L'ho passato in Portento.net working con rev. 2.02 ed aggiornato il menù.
