### ISSUE TITLE
Ricercare nei campi nascosti di Browser 

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#73]
Non è corretto escludere dalle  ricerche i  campi nascosti. Questi devono intendersi esclusi dalla visualizzazione ma in quanto inseriti nella select devono essere considerati pienamente dal comando Sql.  Inoltre il comando Sql ha qualche problema e duplica a volte il risultato delle ricerche in tutti i contesti anche al di fuori della browser.

**Comment by nippur72** [comment]
@mariocarmelo il componente Browser **esegue già** la ricerca nei campi nascosti. :disappointed:

Se non sei convinto, dentro `AnagrafeB.pc` c'è una browser di prova, cerca il `TODO(nino)`.
