### ISSUE TITLE
Help di BarraStrumenti contiene inesattezze

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#76]
Nel documento non esiste "OnCasellaTesto" bensì la definizione di "l'evento CasellaTesto()".
Occorre correggere il manuale o il gestore?
Inoltre certamente contiene un altro svarione che ha portato al cattivo utilizzo (in tutti i programmi) della casella di testo: "Quando l'utente digita qualcosa nella casella e preme Invio, se specificato un browser questo viene richiamato col filtro specificato, altrimenti viene generato l'evento CasellaTesto()". La sequenza indicata chiaramente è: prima il browser e poi l'evento. Mentre è esattamente il contrario con molta differenza.
Altra inesattezza si riscontra nel commento del pulsante ricerca:"La pressione del tasto ricerca da parte dell'utente fa richiamare il browser specificato nella proprietà Browser oppure se questi non è specificato fa generare l'evento Ricerca()". Anche qui è l'esatto contrario anzi lo svarione è doppio perché l'evento scatta comunque: "anche quando il browser è specificato".

**Comment by nippur72** [comment]
Riguardo a "OnCasellaTesto", nella libreria di portento spesso c'è confusione in quanto la prassi di .NET vorrebbe che l'evento si chiamasse con il prefisso "On" ma che venga richiamato senza tale prefefisso.

Esempio:
- evento "OnClick"
- richiama "Button_Click()"

Molti componenti però seguono invece la regola stesso-nome/stesso-evento, solo che non sempre è applicabile (infatti nella `BarraStrumenti` il nome dell'evento `CasellaTesto` era già impegnato per l'omonima proprietà).

Per il resto ho corretto l'help e sistemato la pagina relativa alla barra strumenti.
