### ISSUE TITLE
[Riepilogo DDT] il documento riepilogato non genera eventuali scadenze

### ISSUE THREAD

**Issue by nippur72** [nippur72/issuep#78]
Spostato da #65 

Riapro riepilogo DDT per promemoria di un altro problema: il documento riepilogato non genera eventuali scadenze.

**Comment by nippur72** [comment]
Ho appena provato a fare un DDT e a riepilogarlo e mi **ha generato** la scadenza.

Infatti `RicalcolaTotaliDaFuori()` di DocMag passa anche da `_Altro1()` (aggiorna), e quindi non c'è motivo per cui le scadenze non debbono essere generate.

**Comment by studioReggio** [comment]
OK anche per me.  
Il problema invece è un altro: il riepilogo NON passa la condizione di pagamento del cliente, mette in fattura quella di default che trova abilitata nel magazzino.

**Comment by studioReggio** [comment]
Problema segnalato da Polimeno che sta utilizzando la rev. 53

**Comment by studioReggio** [comment]
chiudo e riporto al #91
