### ISSUE TITLE
DocMag + Provvigioni

### ISSUE THREAD

**Issue by mariocarmelo** [nippur72/issuep#82]
Le provvigioni piede prima funzionavano ora non funzionano. Esattamente se nella mini finestra si digita una % il programma no ne tiene conto. Occorre controllare il flusso perché probabilmente CInputPerProvvPiede_Cambiato non dovrebbe passare il controllo a CalcolaTotaliCorpo()?
Piuttosto CalcolaProvvigioni().

**Comment by nippur72** [comment]
1. ho sistemato il parametro `null` in `CalcolaProvvigioni()`
2. ho estirpato la variabile globale `tipo_opeparticolare`

riguardo la punto 2. ho lasciato un `TODO(nino)` che mi dovete risolvere:

``` C#
// TODO(nino) non poteva mai funzionare perchè "tipi_opeparticolare" è un vettore!!! 
//if(tipi_opeparticolare==8 && risp==1) TabCoge_Comovditte.TipoAcquisizione = 1;  // corrispettivo ad aliquota
//if(tipi_opeparticolare==8 && risp==2) TabCoge_Comovditte.TipoAcquisizione = 2;  // corrispettivo da ventilare
```

**Comment by studioReggio** [comment]
ho aggiunto   int(tipo_documento2) alla riga 3363 dava errore 
non scattano bene ancora le Provvigioni  se cambio il valore nella combobox (da sostitutiva ad aggiuntiva  e viceversa) 
Inoltre,  se riepilogo una bolla con Riepilogoddt o semplicemente fattura da documento e visualizzo le provv. , il valore della combobox delle provvigioni non viene assegnata.

**Comment by studioReggio** [comment]
Ho corretto FatturaDaDDT e DocumentoDaCarico che avevano ancora ProvvAgenteRete invece di ProvvigioneRete

**Comment by studioReggio** [comment]
mi correggo : la riga dove ho aggiunto l'int è la 3331

**Comment by studioReggio** [comment]
vedi anche #92

**Comment by studioReggio** [comment]
sono stati corretti tre errori in documenti di magazzino nella funzione `Genera_SchedaCliente` :
- non assegnava TipoProvvigione=1 
- il controllo su tipoprovvigione per prelevare le provv. dal cli o age era sbagliato (deve essere >1 e non >0) riga 4475  
- ho aggiunto INT alla variabile dest alla riga 4553 che sbagliava l'assegnazione di TabMag_DocMag.IdAnaCliFor 
- ho cambiato la rev. è tutto su stage e net working
