### ISSUE TITLE
Riepilogo DDT rev. 2.01 rev. 53 sbaglia le condizioni di pagamento in fattura  

### ISSUE THREAD

**Issue by studioReggio** [nippur72/issuep#91]
Durante il riepilogo, attualmente la condizione di pagamento viene letta dalla scheda cliente , ignorando quella della bolla che si sta riepilogando. 
Ciò comporta che le condizioni previste nel  DDT vengono cambiate in fattura, sia se nella scheda c'è un'altra condizione, sia se non c'è niente (allora viene prelevata quella di default dei magazzini).
Bisogna però anche valutare  come si deve comportare il riepilogo se incontra condizioni diverse per bolle diverse.

**Comment by studioReggio** [comment]
Come da accordi col Dottore, il riepilogo deve prelevare prima le condizioni di pagamento dalla bolla, e se non ci sono, dal cliente. Se anche qui non ci sono, prende quelle di default dai magazzini, altrimenti deve segnalare che nessun pagamento è stato assegnato (come fa documenti di magazzino) . L'unico problema che resta è stabilire come ci si deve regolare  nel caso ci siano diverse condizioni di pagamento per più bolle da riepilogare.

**Comment by nippur72** [comment]
Ho impostato RiepologoDDT in modo che segnali un errore (o un messaggio, ecc...) al verificarsi di diverse condizioni di pagamento, così puoi proseguire a completare la modifica.

**Comment by studioReggio** [comment]
Il motivo per cui non si generavano le cond.di pagamento riguardava la errata lettura del campo condizione di pagamento del cliente, che prima era un numero, e successivamente è diventato un codice alfabetico. 
Ora legge correttamente e sviluppa le scadenze, e se non c'è nulla nel cliente viene preso l'id di default dei magazzini 
L'errore impostato da Nino è ora un messaggio che non blocca il riepilogo. 
Resta da completare la modifica delle diverse condizioni di pagamento su un modulo complesso come il riepilogo: va inserita al punto giusto e nel modo giusto. Ora esce come rev. 2,02

**Comment by nippur72** [comment]
@studioReggio dunque si può chiudere questo ticket?

**Comment by studioReggio** [comment]
Ok , sposto la prossima modifica da fare su un altro ticket per non perderla di vista.
